define([], function() {
  return {
    PropertyPaneDescription: "Below properties will help you manage your poll questions and extra features that you can leverage.",
    BasicGroupName: "",
    PlaceholderIconText: "Configure your Quick Poll",
    PlaceholderDescription: "",
    PlaceholderButtonLabel: "Come on...",
    QuestionLoadingText: "Loading Poll data",
    SubmissionLoadingText: "Submission is inprogress",
    PlsWait: "Please wait...",
    PollQuestionsLabel: "Poll Questions:",
    PollQuestionsPanelHeader: "Poll Questions list",
    PollQuestionsManageButton: "Manage Questions Info",
    MsgAfterSubmissionLabel: "Success Message:",
    MsgAfterSubmissionDescription: "Message to display after successfull submission. Max of 150 characters are allowed.",
    MsgAfterSubmissionPlaceholder: "Message...",
    SuccessfullVoteSubmission: "Thank you for your submission",
    FailedVoteSubmission: "Sorry, something wrong while submitting. Please try again after sometime.",
    BtnSumbitVote: "Submit Vote",
    BtnSumbitVoteLabel: "Submit button text:",
    BtnSumbitVoteDescription: "Text to display on the submit button. Max of 50 characters are allowed",
    BtnSumbitVotePlaceholder: "Submit button text...",
    ChartFieldLabel: "Preferred Chart Type",
    ChartFieldCalloutText: "Select preferrable chart type",
  }
});