define([], function() {
  return {
    PropertyPaneDescription: "Below properties will help you manage your poll questions and extra features that you can leverage.",
    BasicGroupName: "",
    ListCreationText: "Creating the response list...",
    PlaceholderIconText: "Configure your Quick Poll",
    PlaceholderDescription: "",
    PlaceholderButtonLabel: "Come on...",
    QuestionLoadingText: "Loading Poll data",
    SubmissionLoadingText: "Submission is inprogress",
    PlsWait: "Please wait...",
    PollQuestionsLabel: "Poll Questions:",
    PollQuestionsPanelHeader: "Poll Questions list",
    PollQuestionsManageButton: "Manage Questions Info",
    MsgAfterSubmissionLabel: "Success Message:",
    MsgAfterSubmissionDescription: "Message to display after successfull submission. Max of 150 characters are allowed.",
    MsgAfterSubmissionPlaceholder: "Message...",
    ResponseMsgToUserLabel: "Response Message:",
    ResponseMsgToUserDescription: "Message displayed once the user submitted the poll. E.g., 'You voted for: <User Response>'",
    ResponseMsgToUserPlaceholder: "Message...",
    DefaultResponseMsgToUser: "You voted for",
    SuccessfullVoteSubmission: "Thank you for your submission",
    FailedVoteSubmission: "Sorry, something wrong while submitting. Please try again after sometime.",
    BtnSumbitVote: "Submit Vote",
    BtnSumbitVoteLabel: "Submit button text:",
    BtnSumbitVoteDescription: "Text to display on the submit button. Max of 50 characters are allowed",
    BtnSumbitVotePlaceholder: "Submit button text...",
    ChartFieldLabel: "Preferred Chart Type",
    ChartFieldCalloutText: "Select preferrable chart type",

    Q_Title_Title: "Question Title",
    Q_Title_Placeholder: "Question Title...",
    Q_Options_Title: "Choices",
    Q_Options_Placeholder: "Choices separated by comma",
    MultiChoice_Title: "Multi Selection"
  }
});